var ChannelConstants = {
  SINGLE_CHANNEL_RECEIVED: "SINGLE_CHANNEL_RECEIVED",
  SET_CHANNEL_RECEIVED: "SET_CHANNEL_RECEIVED",
  CHANNELS_RECEIVED: "CHANNELS_RECEIVED"
};

module.exports = ChannelConstants;