var ChannelConstants = {
  SINGLE_CHANNEL_RECEIVED: "SINGLE_CHANNEL_RECEIVED",
  CHANNELS_RECEIVED: "CHANNELS_RECEIVED",
  CURRENT_CHANNEL_REQUEST_RECEIVED: "CURRENT_CHANNEL_REQUEST_RECEIVED"
};

module.exports = ChannelConstants;